# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/165ZIJ2zDsXBI0XofgxgfCxErcmCupYpC
"""

x = int(input("Enter the first num: "))
y = int(input("Enter the second num: "))

for i in range(x, y, 1):
    if i % 2 == 0:
        print("_", end=" ")
    else:
        print(i, end=" ")
