CREATE TABLE STUD(
    ROLL_NO INT,
    NAME VARCHAR(20),
    HOBBIES VARCHAR(20),
    MARKS INT NOT NULL DEFAULT(40),
    CLASS VARCHAR(20),
    DIVI VARCHAR(20)
);

iNSERT INTO STUD VALUES (1,'KRISHNA','CRICKET',99,'TYCO','A'); 
INSERT INTO STUD VALUES (2,'ROHAN','DANCING',88,'TYCO','B'); 
INSERT INTO STUD VALUES (3,'OMYA','SINGING',69,'TYCO','B'); 
INSERT INTO STUD VALUES (4,'SHRIKANT','MIMICRY',89,'TYCO','B'); 
INSERT INTO STUD VALUES (5,'STAVAN','YOGA',79,'TYCO','B'); 

SELECT * FROM STUD 
ORDER BY MARKS ASC
LIMIT 1;

SELECT * FROM STUD
ORDER BY MARKS DESC
LIMIT 1;

SELECT * FROM STUD
ORDER BY NAME DESC;

ALTER TABLE STUD 
ADD RESULT VARCHAR(20);

ALTER TABLE STUD
MODIFY COLUMN RESULT INT;

ALTER TABLE STUD 
RENAME COLUMN DIVI TO DIVISION;

ALTER TABLE STUD
RENAME COLUMN CLASS TO YEAR;

ALTER TABLE STUD
ADD PRIMARY KEY(ROLL_NO);
