# -*- coding: utf-8 -*-
"""boolean using python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k_CxNvqcdGcGsRb9MJCn1xRc7AzCFOAw
"""

num = int(input("Enter an integer: "))

if num == 0:
    print("0")
else:
    binary = 0
    place = 1

    while num > 0:
        rem = num % 2
        binary = binary + (rem * place)
        place = place * 10
        num = num // 2

    print(binary)