# -*- coding: utf-8 -*-
"""Boxplot_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8Mq8-gXhNv_GOn17fJNkh7-9HJXkWup
"""

#Q3. Boxplot using Python
#Write a Python program to create a boxplot for the following dataset and identify any outliers.

#visitors = [-1 ,-30,22, 25, 27, 30, 32, 35, 36, 38, 40,
#42, 45, 48, 50, 52, 55, 58, 90, 95]

import numpy as np
import matplotlib.pyplot as plt

visitors = [-1, -30, 22, 25, 27, 30, 32, 35, 36, 38, 40, 42, 45, 48, 50, 52, 55, 58, 90, 95]

q1 = np.percentile(visitors, 25)
q3 = np.percentile(visitors, 75)
iqr = q3 - q1

lower_fence = q1 - 1.5 * iqr
upper_fence = q3 + 1.5 * iqr

outliers = [x for x in visitors if x < lower_fence or x > upper_fence]

print(f"Q1: {q1}")
print(f"Q3: {q3}")
print(f"IQR: {iqr}")
print(f"Lower Fence: {lower_fence}")
print(f"Upper Fence: {upper_fence}")
print(f"Outliers in the dataset: {outliers}")

plt.boxplot(visitors)
plt.title("Boxplot of Visitors Dataset")
plt.ylabel("Number of Visitors")
plt.show()