# -*- coding: utf-8 -*-
"""change_characters_from_cap_to_small_viceversa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iz0al6oni9n4nhffkZe34Jupk_EuNeaK
"""

string1=str(input("Enter the strtng : "))
length=len(string1)
for i in range(0,length):
  ascii_value=ord(string1[i])
  if 65 <= ascii_value <=90 :
    ascii_value += 32
    print(chr(ascii_value),end="")

  elif 97 <= ascii_value <=122:
    ascii_value -= 32
    print(chr(ascii_value),end="")

  elif chr(32) in string1:
    print(chr(32),end="")

  else:
    print("Invalid Output")