# -*- coding: utf-8 -*-
"""ITR CG4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHcfwcz7z1soIy_TY5L7ivFU20v0-1no
"""

a1=[[1,2,3],[4,5,6],[7,8,9]]
for row in a1:
  for col in row:
    print(col,end=" ")
  print()

b=[1,2,3,4,5,6,7,8,8,8,6,5,4,3,2,1,1,7,9,4,5,6,2,3,5,9,0,1]
key=int(input("Enter the key : "))
a=len(b)
count=0
for i in range(0,a,1):
  if b[i]== key:
   count+=1
print("No. of keys in list is : ",count)

matrix=[[1,2,3],[4,5,6],[7,8,9]]
total_sum=0
for row in matrix:
  for col in row:
    total_sum+=col
    print(total_sum)

matrix=[[1,2,3],[4,5,6],[7,8,9]]
for row in matrix:
  total=0
  for col in row:
     total+=col
  print(total)

data=[1,2,3,4,5,0,-5,-4,-3,-2,-1]
key=int(input())
length=len(data)
for i in range(0,length,1):
  if data[i]==key:
    print(i)

