# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15AiTDOBqXIk6vlP84coFPMNqzeHzY6Fm
"""

user_string = input("Enter a string: ")
length = len(user_string)

for i in range(length):
    row = ["*"] * length
    row[i] = user_string[i]
    row[length - 1 - i] = user_string[length - 1 - i]
    print("".join(row))
