# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UvT63et_SsilEIwFAhBe8oEIV8Vlcbc
"""

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
if num1 > num2:
    largest = num1
else:
    largest = num2
lcm = largest
while True:
    if lcm % num1 == 0 and lcm % num2 == 0:
        print(f"The LCM of {num1} and {num2} is {lcm}")
        break

    lcm += largest
