# -*- coding: utf-8 -*-
"""loops1 python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VzwaHO_mJDC8pRxMWFRpPedbs-S0xfAU
"""

word=input("enter the desired word : ")
length=len(word)
for i in range(length):
  start_asterik="*" * i
  character=word[i]
  end_asterik="*" * (length-i-1)
  print(start_asterik+character+end_asterik)