# -*- coding: utf-8 -*-
"""numpy1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j0jNraCk5gpHHcOCa3hKwcG_Gh4SLzFo
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np

b = np.array(range(20000000))
# %timeit b**2

a = list(range(20))
print(type(a))

b = np.array(range(20000000))
print(type(b))
print(b.ndim)
print(len(b))
print(b.shape)

a = [1, 3, "Sandip"]
print(type(a))

b = np.array(a)
print(type(b))
print(b)

c1 = np.arange(1, 10)
print(c1)

c3 = np.arange(1, 10, 0.5)
print(c3)

a=[1,3,"Sandip"]
print(type(a))
b=np.array(a)
print(type(b))

a = np.arange(1, 10)
print("Original Array:", a)

print("Element at index -2:", a[-2])

print("Slice a[2:5]:", a[2:5])

print("Slice a[3:]:", a[3:])

a = np.arange(1, 10)

print("Elements at indices 2, 5, and 7:", a[[2, 5, 7]])

a = np.array([6, 9, -3, 0, 5, 7, -2, 8, 1])

print("Mask (a < 6):", a < 6)

print("Even elements:", a[a % 2 == 0])

print("Elements > 0:", a[a > 0])

a = np.array(range(16))
print(a.shape)
print(a.ndim)

a = np.array(range(16))

b_manual = a.reshape(8, 2)
print(b_manual)

b_auto = a.reshape(4, -1)
print(b_auto)

a = np.arange(1, 10).reshape(3, 3)
print(a)
print(a[1][2])

a = np.arange(1, 10).reshape(3, 3)

print(a[:2])
print(a[:, :2])
print(a[:, 1:3])