# -*- coding: utf-8 -*-
"""Percentile_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6-E0OEBtBMvYgNS-ADhE5berB2AW8Hb
"""

#Q1. Percentile using Python
#Write a Python program to calculate the 25th percentile, 50th percentile, and 90th percentile
#for the following dataset.

#marks = [42, 48, 51, 55, 58, 60, 63, 67, 70, 72,
#75, 78, 80, 83, 85, 88, 90, 92, 95, 98]

import numpy as np

marks = [42, 48, 51, 55, 58, 60, 63, 67, 70, 72,
         75, 78, 80, 83, 85, 88, 90, 92, 95, 98]

p25 = np.percentile(marks, 25)
p50 = np.percentile(marks, 50)
p90 = np.percentile(marks, 90)

print(f"25th Percentile: {p25}")
print(f"50th Percentile (Median): {p50}")
print(f"90th Percentile: {p90}")