# -*- coding: utf-8 -*-
"""Quantile_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-lseDCPPS6NspIpgZLTFetMG2v9E_w56
"""

#Q2. Quantile using Python
#Write a Python program to calculate the quantiles and Interquartile Range (IQR) for the
#following dataset.

#sales = [15, 18, 20, 22, 25, 28, 30, 32,
#35, 38, 40, 42, 45, 48, 50, 52]

import numpy as np

sales = [15, 18, 20, 22, 25, 28, 30, 32, 35, 38, 40, 42, 45, 48, 50, 52]

q1 = np.quantile(sales, 0.25)
q2 = np.quantile(sales, 0.50)
q3 = np.quantile(sales, 0.75)

iqr = q3 - q1

# Printing the results
print(f"Q1 (25% Quantile): {q1}")
print(f"Q2 (Median): {q2}")
print(f"Q3 (75% Quantile): {q3}")
print(f"Interquartile Range (IQR): {iqr}")