# -*- coding: utf-8 -*-
"""reversenum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5NsG9dgbg7KzquTDsXjqI4QOac3R2JT
"""

number=int(input("enter the value to be reversed : "))
rev_num=0
while number>0:
  last_val=number%10
  rev_num=(rev_num*10)+last_val
  number=number//10
print(f"The reversed value : {rev_num}")