# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t52Ba01dollfRnHjBy8vH3HI9858KBm8
"""

stars=int(input("enetr the no of elements: "))
for x in range(0,stars):
  print(end="  ")
  print()
  for y in range(0,stars-x):
    print("*",end="")
